name: release-to-maven-central

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '0.0.1'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Will start a Maven Central upload with version ${{ github.event.inputs.releaseversion }}"
      - uses: actions/checkout@v2
      - name: Set up Java and Maven Central
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: central
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Set project version
        run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}"
      - name: Build and deploy
        run: |
          if [[ "${{ github.event.inputs.releaseversion }}" == *-SNAPSHOT ]]; then
            echo "Deploying SNAPSHOT version (no -P release)"
            mvn clean deploy --batch-mode --no-transfer-progress -DskipTests
          else
            echo "Deploying RELEASE version (with -P release)"
            mvn clean deploy -P release --batch-mode --no-transfer-progress -DskipTests
          fi